In [1]:
import numpy as np
import pdb
#import matplotlib.pyplot as plt
vec1 = np.array([0, 127.5, 127.5])
mat1 = np.array([[0.299, 0.587, 0.114], [-0.168736, -0.331264, 0.5], [0.5, -0.418688, -0.081312]])
mat1_inv = np.linalg.inv(mat1)

def rgb2ycbcr(rgb):
    #pdb.set_trace()
    #rgb = np.transpose(rgb, [2, 0, 1]) # [H, W, 3] to [3, H, W]
    #ycbcr = vec1 + mat1.dot(rgb) 
    ycbcr = vec1 + rgb.dot(mat1.T) 
    return ycbcr

def ycbcr2rgb(ycbcr):
    #rgb = (mat1_inv.T).dot(ycbcr - vec1)
    rgb = (ycbcr - vec1).dot(mat1_inv.T)
    return rgb
'''
import imageio
im = imageio.imread('birds.ppm')
print(im.shape)
'''
from PIL import Image
img = Image.open("birds.ppm")
#img.show()
img_rgb = np.asarray(img) #TODO verify default is rgb
#pdb.set_trace()
img_ycbcr = rgb2ycbcr(img_rgb)
print(img_ycbcr)
toshow = Image.fromarray(img_ycbcr.astype('uint8'), mode='YCbCr')
#converted = toshow.convert(mode = 'RGB')
toshow.show()
img_rgb_new = ycbcr2rgb(img_ycbcr)

#img_ycbcr_2 = Image.fromarray(img_rgb, mode='YCbCr')
img_ycbcr_2 = img.convert(mode = 'YCbCr')
print(np.asarray(img_ycbcr_2))
#pdb.set_trace()
img_ycbcr_2.show()
print(np.linalg.norm(img_ycbcr - np.asarray(img_ycbcr_2)))
print(np.linalg.norm(img_rgb -img_rgb_new))


[[[112.808    113.5      129.776736]
  [113.808    113.5      129.776736]
  [116.808    113.5      129.776736]
  ...
  [ 40.54     120.987584 131.394432]
  [ 40.54     120.987584 131.394432]
  [ 41.654    121.487584 131.31312 ]]

 [[116.819    113.493792 131.195424]
  [116.819    113.493792 131.195424]
  [117.819    113.493792 131.195424]
  ...
  [ 41.654    121.487584 131.31312 ]
  [ 41.654    121.487584 131.31312 ]
  [ 40.54     120.987584 131.394432]]

 [[120.591    112.493792 131.358048]
  [120.591    112.493792 131.358048]
  [121.591    112.493792 131.358048]
  ...
  [ 41.654    121.487584 131.31312 ]
  [ 40.54     120.987584 131.394432]
  [ 40.54     120.987584 131.394432]]

 ...

 [[ 71.782    105.049664 119.809536]
  [ 72.782    105.049664 119.809536]
  [ 75.782    105.049664 119.809536]
  ...
  [ 64.824    112.362304 123.34592 ]
  [ 56.465    113.693568 123.601984]
  [ 48.465    113.693568 123.601984]]

 [[ 71.44     103.549664 120.053472]
  [ 71.782    105.049664 119.809536]
